server:
  port: 8091

dubbo:
  application:
    name: api-gateshield-test
    version: 1.0.0
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 30000
  protocol:
    name: dubbo
    port: 20881
  config-center:
    timeout: 30000
  scan:
    base-packages: com.yyl.gateshield.rpc

api-gateshield-sdk:
  address: http://localhost:8001
  system-id: api-gateshield-test-provider
  system-name: 网关sdk测试工程
  system-registry: zookeeper://192.168.31.68:2181


